src/apps/core/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [

    url(r'^utils/',
        include([
            url(r'^status-task/$',
                views.StatusTaskAPIView.as_view(),
                name="status-task"),
        ])),

]

urlpatterns = format_suffix_patterns(urlpatterns)

src/apps/web/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (home, post_detalle, altos_funcionarios, funcionarios, municipalidad, 
					mapa, organigrama, tahuamanu, contacto)

app_name = 'web'

urlpatterns = [
	url(r'^$', home, name='home'),
	url(r'^post/(?P<slug>[-\w]+)/$', post_detalle, name='post_detalle'),
	url(r'^altos_funcionarios/$', altos_funcionarios, name='altos_funcionarios'),
	url(r'^funcionarios/$', funcionarios, name='funcionarios'),
	url(r'^municipalidad/$', municipalidad, name='municipalidad'),
	url(r'^mapa/$', mapa, name='mapa'),
	url(r'^organigrama/$', organigrama, name='organigrama'),
	url(r'^contacto/$', contacto, name='contacto'),
	url(r'^tahuamanu/$', tahuamanu, name='tahuamanu'),

]

src/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.web.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    ] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

src/apps/core/models.py
# -*- coding: utf-8 -*-

from django.db import models
from .managers import ActiveInactiveManager


class AuditableModel(models.Model):
    active = models.BooleanField('Activo', default=True)
    created = models.DateTimeField(editable=False, auto_now_add=True)
    modified = models.DateTimeField(editable=False, auto_now=True)
    created_by = models.IntegerField('Creado por', editable=False, null=True,
                                     default=0)
    modified_by = models.IntegerField('Modificado por', editable=False,
                                      null=True, default=0)

    objects = ActiveInactiveManager()

    class Meta:
        abstract = True


class SlugModel(models.Model):
    nombre = models.CharField('Nombre', max_length=120)
    slug = models.SlugField('slug', max_length=180, blank=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.nombre


class PositionModel(models.Model):
    position = models.SmallIntegerField('Posición', default=0)

    class Meta:
        abstract = True
        ordering = ['position']

src/apps/web/models.py
from django.db import models
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


class Categoria(models.Model):
	usuario = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
	nombre = models.CharField('Nombre', max_length=200)
	active = models.BooleanField('Active', default=True)

	def __str__(self):
		return self.nombre


class Post(models.Model):
	categoria = models.ForeignKey(Categoria, related_name='categoria', on_delete=models.CASCADE, blank=True, null=True)
	numero_post = models.IntegerField('Numero', blank=True, null=True)
	fecha_emision = models.DateTimeField('Fecha de emision', blank=True, null=True)
	titulo = models.CharField('Titulo', max_length=5000, blank=True, null=True)
	resumen = models.TextField('Resumen', blank=True, null=True)
	descripcion = models.TextField(blank=True, null=True)
	imagen_principal = ImageField('Imagen Principal', max_length=200, upload_to='posts/', help_text="Tamaño 664x362", blank=True, null=True)
	video = models.URLField('Video url', help_text="La url obtenida por el link de Dropbox cambias el dl=0 x el dl=1", blank=True, null=True)
	slug = models.SlugField(max_length=2000, blank=True, null=True)
	tags = TaggableManager(blank=True, help_text='estos tags son para mejorar la busqueda')
	is_obra = models.BooleanField(default=False)


	class Meta:
		ordering = ['numero_post']

	def __str__(self):
		return self.titulo

	def get_absolute_url(self):
		return reverse('web:post_detalle', kwargs={'slug': self.slug})

class Funcionario(models.Model):
	usuario = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
	nombre_funcionario = models.CharField('Nombre Funcionario', max_length=200)
	cargo = models.CharField('Cargo', max_length=200)
	imagen_principal = ImageField('Imagen Principal', max_length=200, upload_to='posts/', help_text="Tamaño 664x362", blank=True, null=True)

	def __str__(self):
		return self.cargo


class Alto_Funcionario(models.Model):
	usuario = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
	nombre_alto_funcionario = models.CharField('Nombre Funcionario', max_length=200)
	cargo = models.CharField('Cargo', max_length=200)
	imagen_principal = ImageField('Imagen Principal', max_length=200, upload_to='posts/', help_text="Tamaño 664x362", blank=True, null=True)

	def __str__(self):
		return self.cargo

src/apps/web/views.py
import json
from django.shortcuts import render
from django.http.response import JsonResponse, HttpResponse
from pure_pagination import Paginator, PageNotAnInteger
from apps.web.models import (Categoria, Post, Funcionario, Alto_Funcionario)


def home(request):
    tipo_pagina = 'web'
    posts = Post.objects.all().order_by('-id')
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1
    p = Paginator(posts, 3, request=request)
    page_obj = p.page(page)
    print('page_obj', page_obj)

    return render(request, "index.html", locals())


def post_detalle(request, slug):
    post_detallado = Post.objects.get(slug=slug)
    ultimas_noticias = Post.objects.all().order_by('-id')[:3]

    return render(request, 'post_detalle.html', locals())

def altos_funcionarios(request):
    alto_funcionarios = Alto_Funcionario.objects.all()

    return render(request, 'altos_funcionarios.html', locals())

def funcionarios(request):
    funcionarios = Funcionario.objects.all()

    return render(request, 'funcionarios.html', locals())

def contacto(request):
    return render(request, 'contacto.html', locals())

def municipalidad(request):
    funcionarios = Funcionario.objects.all()

    return render(request, 'municipalidad.html', locals())

def mapa(request):
    funcionarios = Funcionario.objects.all()

    return render(request, 'mapa.html', locals())

def organigrama(request):

    return render(request, 'organigrama.html', locals())


def tahuamanu(request):

    return render(request, 'tahuamanu.html', locals())

src/apps/web/templates/altos_funcionarios.html
{% extends "web/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link rel="stylesheet" href="{% static 'css/funcionarios.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css">
<style type="text/css">
.ltr.both.forDays-7.yesLabel {
    background: #1fac07 !important;
}
</style>
{% endblock css %}
{% block content %}
<div class="col-12 container_block"> 
    <h1 class="titulo_h1_funcionarios">ALTOS FUNCIONARIOS</h1>        
  {% for funcionario in alto_funcionarios %}
  <div class="col-4 funcionario_col col-xs-6">
    <div>
        <a href="{{funcionario.imagen_principal.url}}" data-toggle="lightbox" data-width="800" data-height="1500">
            <img src="{{funcionario.imagen_principal.url}}" class="img-fluid funcionario_img">
        </a>
    </div>
    <div class="campo_texto_funcionario">
      <h3>{{funcionario.nombre_alto_funcionario}}</h3>
      <div class="cargo_texto_funcionario">{{funcionario.cargo}}</div>
    </div>

    
  </div>  
  {% endfor %}
</div>
<section class="site-section pt-5 pb-5">
    <div class="container no_pad_marg">
        <div class="contenedor_table">

            <table>
                <tr>
                  <th>CARGO</th>
                  <th>NOMBRES</th>
                </tr>
                
                {% for funcionario in alto_funcionarios %}
                  <tr>
                    <td>{{funcionario.cargo}}</td>
                    <td>{{funcionario.nombre_alto_funcionario}}</td>
                  </tr>
                {% endfor %}
              </table>
        </div>
    </div>
</section>
</div>
    {% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.js"></script>
    <script type="text/javascript">
      $(document).on('click', '[data-toggle="lightbox"]', function(event) {
                      event.preventDefault();
                      $(this).ekkoLightbox();
                  });

    </script>
    {% endblock js %}

{% endblock content %}

src/apps/web/templates/contacto.html
{% extends "web/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link rel="stylesheet" href="{% static 'css/funcionarios.css' %}">
<style type="text/css">
</style>
{% endblock css %}
{% block content %}
<div class="col-12 container_block"> 
    <h1 class="titulo_h1_funcionarios">CONTACTENOS</h1>        
</div>
<section class="site-section pt-5 pb-5">
    <div class="container no_pad_marg">
        <div class="contenedor_contacto">
          <p>Si deseas contactarnos puedes mandar un correo a <strong>municipalidad-san-lorenzo@hotmail.com</strong> dirigido a <strong>Uriel Marcavillaca Alvarez</strong> 
            describiendo su problema o el mensaje por el cual quiere contactar con la municipalidad</p>
          <p>
            Tambien puedes ubicarnos en : CAR.MALDONADO IBERIA NRO. 143 CAS. SAN LORENZO MADRE DE DIOS - TAHUAMANU - TAHUAMANU
          </p>
        </div>
    </div>
</section>
</div>
    {% block js %}
        <script>
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
        </script>
    {% endblock js %}

{% endblock content %}

src/apps/web/templates/funcionarios.html
{% extends "web/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link rel="stylesheet" href="{% static 'css/funcionarios.css' %}">
<style type="text/css">
</style>
{% endblock css %}
{% block content %}
<h1 class="titulo_h1_funcionarios">FUNCIONARIOS</h1> 
<div class="col-12 container_grid"> 
           
  {% for funcionario in funcionarios %}
  <div class="funcionario_col col-xs-6">
    <div class="flex">
      <img src="{{funcionario.imagen_principal.url}}" class="funcionario_img" alt="">
    </div>
    <div class="campo_texto_funcionario">
      <h3>{{funcionario.nombre_funcionario}}</h3>
      <div class="cargo_texto_funcionario">{{funcionario.cargo}}</div>
    </div>
  </div>  
  {% endfor %}
</div>
<section class="site-section pt-5 pb-5">
    <div class="container no_pad_marg">
        <div class="contenedor_table">

            <table>
                <tr>
                  <th>CARGO</th>
                  <th>NOMBRES</th>
                </tr>
                
                {% for funcionario in funcionarios %}
                <tr>
                  <td>{{funcionario.cargo}}</td>
                  <td>{{funcionario.nombre_funcionario}}</td>
                </tr>
                {% endfor %}
              </table>
        </div>
    </div>
</section>
</div>
    {% block js %}
        <script>
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
        </script>
    {% endblock js %}

{% endblock content %}

src/apps/web/templates/mapa.html
{% extends "web/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/mapa.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css">
{% endblock css %}
{% block content %}    
<section class="site-section pt-5 pb-5">
    <div class="container no_pad_marg">
          <h1 class="titulo_h1_mapa">MAPA DE TRAZADO Y LOTIZACION DE TAHUAMANU</h1>    
        <div class="contenedor_imagen">
          <a href="{% static 'images/mapa.jpg' %}" data-toggle="lightbox" data-width="800" data-height="1500">
                <img src="{% static 'images/mapa.jpg' %}" class="img-fluid img_mapa">
            </a>
        </div>
    </div>
</section>
</div>
    {% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.js"></script>
    <script type="text/javascript">
      $(document).on('click', '[data-toggle="lightbox"]', function(event) {
                      event.preventDefault();
                      $(this).ekkoLightbox();
                  });

    </script>
    {% endblock js %}

{% endblock content %}

src/apps/web/templates/municipalidad.html
{% extends "web/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link rel="stylesheet" href="{% static 'css/funcionarios.css' %}">
<style type="text/css">
.ltr.both.forDays-7.yesLabel {
    background: #1fac07 !important;
}
</style>
{% endblock css %}
{% block content %}
<div class="col-12 container_block"> 
    <h1 class="titulo_h1_funcionarios">FUNCIONARIOS</h1>        
  {% for funcionario in funcionarios %}
  <div class="col-4 funcionario_col">
    <div>
      <img src="{{funcionario.imagen_principal.url}}" class="funcionario_img" alt="">
    </div>
    <div class="campo_texto_funcionario">
      <h3>{{funcionario.nombre_funcionario}}</h3>
      <div class="cargo_texto_funcionario">{{funcionario.cargo}}</div>
    </div>

    
  </div>  
  {% endfor %}
</div>
<section class="site-section pt-5 pb-5">
    <div class="container no_pad_marg">
        <div class="contenedor_table">

            <table>
                <tr>
                  <th>Cargo</th>
                  <th>Nombres</th>
                </tr>
                <tr>
                  <td>GERENTE MUNICIPAL</td>
                  <td>MARIO ALBERTO TORRES TUMI</td>
                </tr>
                <tr>
                  <td>GERENTE DE DESARROLLO URBANO Y RURAL</td>
                  <td>DARWIN ROJAS ARGANDOÑA</td>
                </tr>
                <tr>
                  <td>GERENTE DE ADMINISTRACION</td>
                  <td>CLAUDIA ESTHER VELARDE OCHARAN</td>
                </tr>
                <tr>
                  <td>GERENTE  DE DESARROLLO ECONOMICO Y MEDIO AMBIENTE</td>
                  <td>LILIBETH MILAGROS HERNANDEZ ANICAMA</td>
                </tr>
                <tr>
                  <td>GERENTE DE ASESORIA JURIDICA</td>
                  <td>LUIS ALFREDO YUPANQUI HUILLCA</td>
                </tr>
                <tr>
                  <td>GERENTE DE DESARROLLO SOCIAL</td>
                  <td>YLSER GLADIS PANDURO BURGA</td>
                </tr>
                <tr>
                    <td>SECRETARIO GENERAL</td>
                    <td>OSVEL ZAMBRANO RUEDA</td>
                  </tr>
              </table>
        </div>
    </div>
</section>
</div>
    {% block js %}
        <script>
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
        </script>
    {% endblock js %}

{% endblock content %}

src/apps/web/templates/noticias_index.html
{% extends "web/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/mapa.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css">
{% endblock css %}
{% block content %}    
<section class="site-section pt-5 pb-5">
    <div class="container no_pad_marg">
          <h1 class="titulo_h1_noticias_index">MAPA DE TRAZADO Y LOTIZACION DE TAHUAMANU</h1>   
           

    </div>
</section>
</div>
    {% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.js"></script>
    <script type="text/javascript">
      $(document).on('click', '[data-toggle="lightbox"]', function(event) {
                      event.preventDefault();
                      $(this).ekkoLightbox();
                  });

    </script>
    {% endblock js %}

{% endblock content %}

src/apps/web/templates/organigrama.html
{% extends "web/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/mapa.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css">
{% endblock css %}
{% block content %}    
<section class="site-section pt-5 pb-5">
    <div class="container no_pad_marg">
          <h1 class="titulo_h1_mapa">ORGANIGRAMA ESTRUCTURAL DE LA MUNICIPALIDAD DISTRITAL DE TAHUAMANU</h1>    
        <div class="contenedor_imagen">
          <a href="{% static 'images/organigrama.png' %}" data-toggle="lightbox" data-width="800" data-height="1500">
                <img src="{% static 'images/organigrama.png' %}" class="img-fluid img_mapa">
            </a>
        </div>
    </div>
</section>
</div>
    {% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.js"></script>
    <script type="text/javascript">
      $(document).on('click', '[data-toggle="lightbox"]', function(event) {
                      event.preventDefault();
                      $(this).ekkoLightbox();
                  });

    </script>
    {% endblock js %}

{% endblock content %}

src/templates/web/_pagination.html
{% load i18n %}
        <div class="row mt-5">
          <div class="col-md-12 text-center">
            <nav aria-label="Page navigation" class="text-center">
              <ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item  active"><a class="page-link" href="?{{ page_obj.previous_page_number.querystring }}">&lt;</a></li>
    {% endif %}
    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
            <li class="page-item"><a class="page-link">{{ page }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?{{ page.querystring }}">{{ page }}</a></li>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?{{ page_obj.next_page_number.querystring }}">&gt;</a></li>
    {% endif %}
              </ul>
            </nav>
          </div>
        </div>

src/templates/web/header.html
{% load static %}

{% comment %}
<div class="top-bar">
    <div class="container">
    <div class="row">
        <div class="col-9 social">
        <a href="#"><span class="fa fa-twitter"></span></a>
        <a href="#"><span class="fa fa-facebook"></span></a>
        <a href="#"><span class="fa fa-instagram"></span></a>
        <a href="#"><span class="fa fa-youtube-play"></span></a>
        </div>
        <div class="col-3 search-top">
        <!-- <a href="#"><span class="fa fa-search"></span></a> -->
        <form action="#" class="search-top-form">
            <span class="icon fa fa-search"></span>
            <input type="text" id="s" placeholder="Type keyword to search...">
        </form>
        </div>
    </div>
    </div>
</div>  
{% endcomment %}
    

<div class="wrap">
    <header role="banner">
    <div class="container logo-wrap">
        <div class="row pt-5">
        <div class="col-12 text-center">
            <a class="absolute-toggle d-block d-md-none" data-toggle="collapse" href="#navbarMenu" role="button" aria-expanded="false" aria-controls="navbarMenu"><span class="burger-lines"></span></a>
            <a href="{% url 'web:home' %}" class="a_logo"><img  class="img_logo" src="{% static "images/logo-02.png" %}"></a>
        </div>
        </div>
    </div>
    
    <nav class="navbar navbar-expand-md  navbar-light bg-light">
        <div class="container navbar_container">
        
        
        <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="navbar-nav mx-auto no_padding">
            <li class="nav-item">
                <a class="nav-link active" href="{%url 'web:home' %}">Inicio</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{%url 'web:municipalidad' %}" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Municipalidad</a>
                <div class="dropdown-menu simple" aria-labelledby="dropdown04">
                <a class="dropdown-item" href="{%url 'web:mapa' %}">Mapa</a>
                <a class="dropdown-item" href="{%url 'web:organigrama' %}">Organigrama</a>
                <a class="dropdown-item" href="{%url 'web:altos_funcionarios' %}">Altos Funcionarios</a>
                <a class="dropdown-item" href="{%url 'web:funcionarios' %}">Funcionarios</a>
                </div>

            </li>
            <li class="nav-item responsive_noticias">
                <a class="nav-link active" href="">Noticias</a>
            </li>
            <li class="nav-item dropdown only_desktop">
                <a class="nav-link dropdown-toggle" href="category.html" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Noticias</a>
                <div class="dropdown-menu" aria-labelledby="dropdown04">
                    <div class="col-12 inline_flex">
                        {% for populated_post in populated_posts|slice:":4"  %}
                        <div class="col-md-3 dropdown_contenedor"> 
                            <a href="{%url 'web:post_detalle' populated_post.slug %}">
                                <div class="img_dropdown"  style="background-image: url('{{populated_post.imagen_principal.url}}'); ">
                                </div>  
                            
                                <div class="text_dropdown">
                                    <h4 class="titulo_h4_dropdown">{{populated_post.titulo}}</h4>
                                    <div class="post-meta">
                                    <span class="mr-2">{{populated_post.fecha_emision.date}}</span>
                                    </div>
                                </div>
                            </a>    
                        </div>
                        {% endfor %}
                    </div>
                </div>

            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'web:tahuamanu' %}">Tahuamanu</a>
            </li>            
            <li class="nav-item">
                <a class="nav-link" href="">Transparencia</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'web:contacto' %}">Contactenos</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{%url 'web:municipalidad' %}" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sistemas</a>
                <div class="dropdown-menu simple" aria-labelledby="dropdown04">
                <a class="dropdown-item" href="https://csimunicipio.com/sistemas/sistemacaja/">Caja</a>
                <a class="dropdown-item" href="https://csimunicipio.com/sistemas/sistemarentas/">Rentas</a>
                <a class="dropdown-item" href="https://csimunicipio.com/sistemas/sistemagua/">Agua</a>
                </div>

            </li>

            </ul>
            
        </div>
        </div>
    </nav>
    </header>
    <!-- END header -->

src/templates/web/sss.html
{% load static %}
    <header class="header">
        <!-- nav Structure -->
        <div class="navbar-fixed">
            <nav>
                <div class="nav-wrapper">
                    <a href="{% url 'web:home' %}" class="brand-logo"><img class="logo" src="{% static 'img/logo.png' %}"></a>
                    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                    <ul id="nav-mobile" class="right hide-on-med-and-down sidenav-color">
                              <!-- Dropdown Trigger -->
                        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">PROGRAMAS<i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a href="movies.html">AUSPICIOS</a></li>
                        <li><a href="series.html">EN VIVO</a></li>
                        <li><a href="prices.html">CONTÁCTENOS</a></li>
                        <li>
                            <form>
                                <div class="input-field">
                                <input id="search" type="search" required>
                                <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                                <i class="material-icons">close</i>
                                </div>
                            </form>  
                        </li>
                    </ul>
                </div>
            </nav>

        </div>
        <!-- Responsive sidenav Structure -->
        <ul class="sidenav sidenav-color" id="mobile-demo">
              <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">PROGRAMAS<i class="material-icons right">arrow_drop_down</i></a></li>
              <li><a href="movies.html">AUSPICIOS</a></li>
              <li><a href="series.html">EN VIVO</a></li>
              <li><a href="prices.html">CONTÁCTENOS</a></li>
            <nav>
                <div class="nav-wrapper">
                    <form>
                    <div class="input-field">
                        <input id="search" type="search" required>
                        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                        <i class="material-icons">close</i>
                    </div>
                    </form>
                </div>
            </nav>
        </ul>


        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a href="{% url 'web:home' %}" class="brand-logo"><img class="logo" src="{% static 'img/logo.png' %}"></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
    </header>

    <script type="text/javascript">
    $(".dropdown-trigger").dropdown();
    </script>